param(
    [string]$StackRoot = "",
    [string]$OutputDir = "outputs/repo-workflow-smoke"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ActivateScript = Join-Path $PSScriptRoot "activate.ps1"
if ([string]::IsNullOrWhiteSpace($StackRoot)) {
    . $ActivateScript -Quiet
}
else {
    . $ActivateScript -StackRoot $StackRoot -Quiet
}

$RepoRoot = $env:VELLUM_REPO_ROOT
$Python = $env:VELLUM_PYTHON

function Get-FullPath {
    param([string]$Path)
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $RepoRoot $Path))
}

function Test-InsideRepo {
    param([string]$Path)
    $RepoFull = [System.IO.Path]::GetFullPath($RepoRoot).TrimEnd("\")
    $PathFull = [System.IO.Path]::GetFullPath($Path).TrimEnd("\")
    return $PathFull.Equals($RepoFull, [System.StringComparison]::OrdinalIgnoreCase) -or
        $PathFull.StartsWith("$RepoFull\", [System.StringComparison]::OrdinalIgnoreCase)
}

function Invoke-Native {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$Arguments = @(),
        [string]$WorkingDirectory = ""
    )

    if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) {
        Push-Location -LiteralPath $WorkingDirectory
    }

    try {
        $Output = & $FilePath @Arguments 2>&1
        $ExitCode = $LASTEXITCODE
        if ($ExitCode -ne 0) {
            throw "Command failed with exit code ${ExitCode}: $FilePath $($Arguments -join ' ') $($Output -join ' ')"
        }
        return (($Output | ForEach-Object { $_.ToString() }) -join " ").Trim()
    }
    finally {
        if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) {
            Pop-Location
        }
    }
}

function Assert-File {
    param(
        [string]$Path,
        [string]$Label
    )
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Label was not created: $Path"
    }
}

$OutputPath = Get-FullPath -Path $OutputDir
if (-not (Test-InsideRepo -Path $OutputPath)) {
    throw "Smoke output directory must stay inside the repository: $OutputPath"
}

$QaDir = Join-Path $OutputPath "qa-pages"
$HtmlPath = Join-Path $OutputPath "smoke.html"
$PdfPath = Join-Path $OutputPath "smoke.pdf"
$ContactSheetPath = Join-Path $OutputPath "qa-contact-sheet.png"
$RegistryPath = Join-Path $OutputPath "registry.jsonl"

New-Item -ItemType Directory -Force -Path $OutputPath, $QaDir | Out-Null

$Html = @'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Vellum PDF Workflow Smoke</title>
  <style>
    @page { size: A4; margin: 18mm; }
    body { font-family: "Segoe UI", Arial, sans-serif; color: #1f2933; }
    h1 { font-size: 26px; margin: 0 0 10px; }
    p { font-size: 12px; line-height: 1.55; margin: 0 0 12px; }
    table { border-collapse: collapse; width: 100%; margin-top: 18px; }
    th, td { border: 1px solid #9aa5b1; padding: 8px 10px; font-size: 11px; text-align: left; }
    th { background: #eef2f7; }
    .mark { border-left: 4px solid #2f80ed; padding-left: 10px; margin-top: 18px; }
  </style>
</head>
<body>
  <h1>Vellum repository PDF workflow smoke</h1>
  <p>This PDF is generated by scripts/smoke.ps1 through repository workflow files.</p>
  <div class="mark">
    <p>The external stack supplies tools. The workflow source is the current Vellum repository.</p>
  </div>
  <table>
    <thead>
      <tr><th>Check</th><th>Expected result</th></tr>
    </thead>
    <tbody>
      <tr><td>HTML to PDF</td><td>Playwright renders this page to smoke.pdf.</td></tr>
      <tr><td>QA render</td><td>render_pdf.py creates smoke-page-1.png.</td></tr>
      <tr><td>Contact sheet</td><td>create_montage.py creates qa-contact-sheet.png.</td></tr>
      <tr><td>Artifact registry</td><td>artifact_registry.py records the generated PDF.</td></tr>
    </tbody>
  </table>
</body>
</html>
'@

Set-Content -LiteralPath $HtmlPath -Value $Html -Encoding UTF8

$HtmlToPdf = Join-Path $RepoRoot "skills\pdfs\scripts\html_to_pdf.py"
$RenderPdf = Join-Path $RepoRoot "skills\pdfs\scripts\render_pdf.py"
$CreateMontage = Join-Path $RepoRoot "skills\pdfs\scripts\create_montage.py"
$ArtifactRegistry = Join-Path $RepoRoot "skills\pdfs\scripts\artifact_registry.py"

Write-Output "Generating smoke PDF..."
Invoke-Native -FilePath $Python -Arguments @($HtmlToPdf, $HtmlPath, "--output", $PdfPath, "--format", "A4") -WorkingDirectory $RepoRoot | Out-Null
Assert-File -Path $PdfPath -Label "smoke PDF"

Write-Output "Rendering first QA page..."
Invoke-Native -FilePath $Python -Arguments @($RenderPdf, $PdfPath, "--out_dir", $QaDir, "--prefix", "smoke-page", "--engine", "pdftoppm", "--dpi", "150", "--pages", "1") -WorkingDirectory $RepoRoot | Out-Null
$FirstPage = Join-Path $QaDir "smoke-page-1.png"
Assert-File -Path $FirstPage -Label "QA page render"

Write-Output "Creating contact sheet..."
Invoke-Native -FilePath $Python -Arguments @($CreateMontage, $QaDir, "--out", $ContactSheetPath, "--cols", "2", "--tile_max_w", "360") -WorkingDirectory $RepoRoot | Out-Null
Assert-File -Path $ContactSheetPath -Label "QA contact sheet"

Write-Output "Registering smoke artifact..."
$RegisterOutput = Invoke-Native -FilePath $Python -Arguments @(
    $ArtifactRegistry,
    "register",
    $PdfPath,
    "--registry",
    $RegistryPath,
    "--type",
    "application/pdf",
    "--description",
    "Repository workflow smoke PDF",
    "--producer",
    "scripts/smoke.ps1 using skills/pdfs/scripts/html_to_pdf.py",
    "--preview",
    $ContactSheetPath,
    "--preview-note",
    "First-page QA contact sheet",
    "--json"
) -WorkingDirectory $RepoRoot

Assert-File -Path $RegistryPath -Label "smoke registry"

Write-Output ""
Write-Output "PASS: Vellum repository workflow smoke completed."
Write-Output "PDF=$PdfPath"
Write-Output "QA_PAGE=$FirstPage"
Write-Output "CONTACT_SHEET=$ContactSheetPath"
Write-Output "REGISTRY=$RegistryPath"
Write-Output $RegisterOutput
